#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "framagames"
name = "Framagames"
description.en = "Set of games Framagames from Framasoft"
description.fr = "Ensemble de jeux Framagames venant de Framasoft"

version = "2025.05.02~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://framagit.org/framasoft/framagames"
code = "https://framagit.org/framasoft/framagames"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/framagames"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    url = "https://framagit.org/framasoft/framagames/-/archive/30f98b29f27e541356ccacb30ebae624188a0b70/framagames-30f98b29f27e541356ccacb30ebae624188a0b70.tar.bz2"
    sha256 = "3c12206348a5d376bc80e406fa27e273574ea12ae9135850f51745874edfc9eb"

    autoupdate.strategy = "latest_gitlab_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
