packaging_format = 2

id = "framagames"
name = "Framagames"
description.en = "Set of games Framagames from Framasoft"
description.fr = "Ensemble de jeux Framagames venant de Framasoft"

version = "1.0~ynh4"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://framagit.org/framasoft/framagames"
code = "https://framagit.org/framasoft/framagames"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/framagames"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-fpm"
