test_format = 1.0

[default]

    exclude = ["change_url"] 
    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.fb3cdde65e8003c2386002e7dc49c02989f9198d.name = "Upgrade from 1.0~ynh4"
